// <auto-generated>
//     This code was generated by Reflect-CsObjectType.ps1 and manually refined
//     Metaverse Object model for Azure AD Connect
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Laparoscope.Models
{
    /// <summary>
    /// Represents a Metaverse (MV) object in Azure AD Connect
    /// </summary>
    public class MvObject
    {
        public Guid ObjectId { get; set; }
        public List<MvObjectLineage> Lineage { get; set; }

        // For backward compatibility and easier access, expose Attributes as a List
        public List<MvAttribute> Attributes { get; set; }

        public MvObject()
        {
            Lineage = new List<MvObjectLineage>();
            Attributes = new List<MvAttribute>();
        }
    }

    /// <summary>
    /// Represents lineage information for an MV object (connected CS objects)
    /// </summary>
    public class MvObjectLineage
    {
        public string ConnectorName { get; set; }
        public string ConnectedCsObjectDN { get; set; }
        public Guid ConnectedCsObjectId { get; set; }

        public MvObjectLineage() { }
    }

    /// <summary>
    /// Represents an attribute of an MV object
    /// </summary>
    public class MvAttribute
    {
        public string Name { get; set; }
        public int Type { get; set; } // SchemaAttributeType enum as int
        public bool IsMultiValued { get; set; }
        public string SyncRuleName { get; set; }
        public string ConnectorName { get; set; }
        public Guid LineageId { get; set; }
        public DateTime LastModificationTime { get; set; }
        public List<string> Values { get; set; }

        public MvAttribute()
        {
            Values = new List<string>();
        }
    }
}
