// <auto-generated>
//     This code was generated by Reflect-CsObjectType.ps1 and manually refined
//     Enhanced from the original AadcCSObject.cs
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Laparoscope.Models
{
    /// <summary>
    /// Represents a Connector Space (CS) object in Azure AD Connect
    /// </summary>
    public class CsObject
    {
        public Guid ObjectId { get; set; }
        public Guid ConnectorId { get; set; }
        public string ConnectorName { get; set; }
        public string ConnectorType { get; set; }
        public Guid PartitionId { get; set; }
        public string DistinguishedName { get; set; }
        public byte[] AnchorValue { get; set; }
        public string ObjectType { get; set; }
        public bool IsTransient { get; set; }
        public bool IsPlaceHolder { get; set; }
        public bool IsConnector { get; set; }
        public bool HasSyncError { get; set; }
        public bool HasExportError { get; set; }
        public ExportError ExportError { get; set; }
        public SynchronizationError SynchronizationError { get; set; }
        public Guid ConnectedMVObjectId { get; set; }
        public List<CsObjectLineage> Lineage { get; set; }

        // For backward compatibility and easier access, expose Attributes as a List
        // The actual PowerShell type is AttributeKeyedCollection but we serialize it as a list
        public List<CsAttribute> Attributes { get; set; }

        public CsObject()
        {
            Lineage = new List<CsObjectLineage>();
            Attributes = new List<CsAttribute>();
        }
    }

    /// <summary>
    /// Represents lineage information for a CS object (sync rules applied)
    /// </summary>
    public class CsObjectLineage
    {
        public string SyncRuleInternalId { get; set; }
        public string SyncRuleName { get; set; }
        public string Operation { get; set; }

        public CsObjectLineage() { }
    }

    /// <summary>
    /// Represents an attribute of a CS object
    /// </summary>
    public class CsAttribute
    {
        public string Name { get; set; }
        public int Type { get; set; } // SchemaAttributeType enum as int
        public bool IsMultiValued { get; set; }
        public string SyncRuleName { get; set; }
        public string ConnectorName { get; set; }
        public Guid LineageId { get; set; }
        public DateTime LastModificationTime { get; set; }
        public List<string> Values { get; set; }

        public CsAttribute()
        {
            Values = new List<string>();
        }
    }

    /// <summary>
    /// Keyed collection of attributes
    /// </summary>
    public class AttributeKeyedCollection
    {
        public List<CsAttribute> KeyedCollectionAsList { get; set; }
        public int Count { get; set; }

        public AttributeKeyedCollection()
        {
            KeyedCollectionAsList = new List<CsAttribute>();
        }
    }

    /// <summary>
    /// Represents a synchronization error on a CS object
    /// </summary>
    public class SynchronizationError
    {
        public int RetryCount { get; set; }
        public DateTime InitialOccurrence { get; set; }
        public DateTime LatestOccurrence { get; set; }
        public string ErrorType { get; set; }
        public bool ExportedChangedNotReimported { get; set; }
        public string SynchronizationStep { get; set; }
        public string StackTrace { get; set; }
    }

    /// <summary>
    /// Represents an export error on a CS object
    /// </summary>
    public class ExportError
    {
        public int RetryCount { get; set; }
        public DateTime InitialOccurrence { get; set; }
        public DateTime LatestOccurrence { get; set; }
        public string ErrorType { get; set; }
        public string ErrorName { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorLiteral { get; set; }
        public string ErrorExtraDetails { get; set; }
    }

}
