// <auto-generated>
//     This code was generated by Reflect-ConnectorType.ps1
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Laparoscope.Models
{
    public class AadcConnector
    {
        public string ConnectorTypeName { get; set; }
        public Guid Identifier { get; set; }
        public int Version { get; set; }
        public int InternalVersion { get; set; }
        public int FormatVersion { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastModificationTime { get; set; }
        public List<ConnectorPartition> Partitions { get; set; }
        public List<RunProfile> RunProfiles { get; set; }
        public Dictionary<string, string> ComponentProvisioningMappings { get; set; }
        public Schema Schema { get; set; }
        public List<ConfigurationParameter> AllParameterDefinitions { get; set; }
        public ParameterKeyedCollection ConnectivityParameters { get; set; }
        public ParameterKeyedCollection GlobalParameters { get; set; }
        public ParameterKeyedCollection CapabilityParameters { get; set; }
        public ParameterKeyedCollection SchemaParameters { get; set; }
        public IList<string> ObjectInclusionList { get; set; }
        public List<string> AttributeInclusionList { get; set; }
        public ConnectorAnchorSettingsKeyedCollection AnchorConstructionSettings { get; set; }
        public string ListName { get; set; }
        public string CompanyName { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public bool IsUpgradeOrImportScenario { get; set; }
        public ConnectorExtensionConfiguration ExtensionConfiguration { get; set; }
        public string PasswordHashConfiguration { get; set; }
        public string AADPasswordResetConfiguration { get; set; }
    }

    public class ConnectorPartition
    {
        public Guid Identifier { get; set; }
        public string DN { get; set; }
        public int Version { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastModificationTime { get; set; }
        public bool Selected { get; set; }
        public ConnectorPartitionScope ConnectorPartitionScope { get; set; }
        public string Name { get; set; }
        public object Parameters { get; set; }
        public List<string> PreferredDCs { get; set; }
        public bool IsDomain { get; set; }
    }

    public class ConnectorPartitionScope
    {
        public List<string> ObjectClasses { get; set; }
        public List<string> ContainerInclusionList { get; set; }
        public List<string> ContainerExclusionList { get; set; }
    }

    public class RunProfile
    {
        public string Name { get; set; }
        public Guid Identifier { get; set; }
        public string Type { get; set; }
    }

    public class ConnectorExtensionConfiguration
    {
        public int ExportType { get; set; }
        public long CapabilityBits { get; set; }
        public bool IsImportFileBased { get; set; }
        public bool IsExportFileBased { get; set; }
        public bool IsImportEnabled { get; set; }
        public bool IsExportEnabled { get; set; }
        public string ExtensionFileName { get; set; }
        public int CachedImportDefaultPageSize { get; set; }
        public int CachedExportDefaultPageSize { get; set; }
        public int CachedImportMaxPageSize { get; set; }
        public int CachedExportMaxPageSize { get; set; }
        public bool PartitionDiscoveryEnabled { get; set; }
        public bool SchemaDiscoveryEnabled { get; set; }
        public bool HierarchyDiscoveryEnabled { get; set; }
        public bool PasswordManagementEnabled { get; set; }

        // Using string instead of Version to avoid JSON deserialization issues
        // Can be parsed using Version.Parse(AssemblyVersion) if needed
        public string AssemblyVersion { get; set; }
    }

    public class ParameterKeyedCollection
    {
        public IList<ConfigurationParameter> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class Schema
    {
        public Guid Identifier { get; set; }
        public SchemaObjectTypesKeyedCollection ObjectTypes { get; set; }
        public SchemaAttributeTypesKeyedCollection AttributeTypes { get; set; }
        public bool IsConnectorSchema { get; set; }
        public SchemaAttributeTypesKeyedCollection IntrinsicAttributes { get; set; }
        public IList<string> AllDNComponents { get; set; }
    }

    public class ConnectorAnchorSettingsKeyedCollection
    {
        public IList<ConnectorAnchorConstructionSettings> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class ConfigurationParameter
    {
        public string Name { get; set; }
        public int InputType { get; set; } // ConfigurationParameterType enum
        public int Scope { get; set; } // ParameterScope enum
        public string Description { get; set; }
        public string RegexValidationPattern { get; set; }
        public string DefaultValue { get; set; }
        public string Value { get; set; }
        public bool Extensible { get; set; }
        public int PageNumber { get; set; }
        public bool Intrinsic { get; set; }
        public int DataType { get; set; } // SchemaAttributeType enum
    }

    public class SchemaObjectTypesKeyedCollection
    {
        public IList<SchemaObjectType> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class SchemaAttributeTypesKeyedCollection
    {
        public IList<SchemaAttribute> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class ConnectorAnchorConstructionSettings
    {
        public string ObjectType { get; set; }
        public List<string> Attributes { get; set; }
        public bool Locked { get; set; }
    }

    public class SchemaObjectType
    {
        public string Identifier { get; set; }
        public string Name { get; set; }
        public SchemaBindingKeyedCollection SchemaBindings { get; set; }
        public bool Locked { get; set; }
        public List<string> SupportedDNComponentsForProvisioning { get; set; }
        public SchemaObjectType ParentSchemaObjectType { get; set; }
        public SchemaObjectTypesIdentifierKeyedCollection AuxiliaryObjectTypes { get; set; }
        public string ClassType { get; set; }
        public SchemaBindingKeyedCollection AnchorAttributes { get; set; }
    }

    public class SchemaAttribute
    {
        public string Identifier { get; set; }
        public string Name { get; set; }
        public int Type { get; set; } // SchemaAttributeType enum
        public bool AllowsMultipleValues { get; set; }
        public bool Indexable { get; set; }
        public bool Indexed { get; set; }
        public int SupportedAttributeOperationType { get; set; } // AttributeOperationType enum
        public bool Encrypted { get; set; }
        public string SyntaxValue { get; set; }
        public string SqlColumnDefinition { get; set; }
    }

    public class SchemaObjectTypesIdentifierKeyedCollection
    {
        public IList<SchemaObjectType> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class SchemaBindingKeyedCollection
    {
        public IList<SchemaBinding> KeyedCollectionAsList { get; set; }
        public IEqualityComparer<string> Comparer { get; set; }
        public int Count { get; set; }
    }

    public class SchemaBinding
    {
        public string AttributeIdentifier { get; set; }
        public bool Required { get; set; }
        public bool IsAnchor { get; set; }
        public bool IsLocked { get; set; }
    }
}
