//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aadcapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aadcapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param ($Name)
        ///
        ///Import-Module ADSync;
        ///$param = @{}
        ///if ($Name) { $param.Add(&apos;Name&apos;, $Name) }
        ///$fmt_connectivity_params = @{
        ///    Name=&quot;ConnectivityParameters&quot;
        ///    Expression={
        ///        $val = New-Object PSObject
        ///        $_.ConnectivityParameters | foreach {
        ///            $p = $_
        ///            $val | Add-Member -MemberType NoteProperty -Name $p.Name -Value $p.Value
        ///        }
        ///        $val
        ///    }
        ///}
        ///$fmt_partition_params = @{
        ///    Name=&quot;Partitions&quot;
        ///    Expression={
        ///        $fmt_params = @{
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get_ADSyncConnectorsBasic {
            get {
                return ResourceManager.GetString("Get-ADSyncConnectorsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param (
        ///    [Parameter(Mandatory=$true)]
        ///    $ConnectorName,
        ///    [Parameter(Mandatory=$true)]
        ///    $DistinguishedName)
        ///
        ///Import-Module ADSync
        ///
        ///$attributes = @(
        ///&quot;ObjectId&quot;,
        ///&quot;ConnectorId&quot;,
        ///&quot;ConnectorName&quot;,
        ///&quot;ConnectorType&quot;,
        ///&quot;PartitionId&quot;,
        ///&quot;DistinguishedName&quot;,
        ///&quot;AnchorValue&quot;,
        ///&quot;ObjectType&quot;,
        ///&quot;IsTransient&quot;,
        ///&quot;IsPlaceHolder&quot;,
        ///&quot;IsConnector&quot;,
        ///&quot;HasSyncError&quot;,
        ///&quot;HasExportError&quot;,
        ///&quot;ExportError&quot;,
        ///&quot;SynchronizationError&quot;,
        ///&quot;ConnectedMVObjectId&quot;,
        ///&quot;Lineage&quot;,
        ///&quot;Attributes&quot;
        ///)
        ///
        ///Get-ADSyncCSObject -Connector [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get_ADSyncCSObjectStrict {
            get {
                return ResourceManager.GetString("Get-ADSyncCSObjectStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param (
        ///    [Parameter(Mandatory=$true)]
        ///    $Identifier
        ///    )
        ///
        ///Import-Module ADSync
        ///
        ///$attributes = @(
        ///&quot;ObjectId&quot;,
        ///&quot;Lineage&quot;,
        ///&quot;Attributes&quot;
        ///)
        ///
        ///Get-ADSyncMVObject -Identifier $Identifier | select $attributes.
        /// </summary>
        internal static string Get_ADSyncMVObjectStrict {
            get {
                return ResourceManager.GetString("Get-ADSyncMVObjectStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import-Module ADSync
        ///
        ///&lt;#
        ///Don&apos;t dispatch a sync if the last run was less than 10 minutes ago.
        ///#&gt;
        ///
        ///$lastRun = $null
        ///$lastRun = Get-ADSyncRunProfileResult | select -First 1
        ///$schedule = Get-ADSyncScheduler
        ///$threshold = 10
        ///
        ///$mostReccent = if ($lastRun.StartDate -gt $lastRun.EndDate) { $lastRun.StartDate } else { $lastRun.EndDate }
        ///
        ///$return = New-Object PSObject -Property @{
        ///    Result=&apos;&apos;
        ///    Started=$false
        ///}
        ///
        ///if (($schedule.SyncCycleEnabled) -and (-not $schedule.SyncCycleInProgress) -and ((-not [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Start_ADSyncDelta {
            get {
                return ResourceManager.GetString("Start-ADSyncDelta", resourceCulture);
            }
        }
    }
}
